artifacts:
  artifacts_dir: artifacts
  Trained_model_dir: model
  Base_model_dir: base_model
  Base_model_name: vgg12_base_model.h5
  updated_base_model_name: updated_vgg16_base_model.h5
  Checkpoint_dir: checkpoints
  Base_log_dir: base_model_dir
  Tensorboard_root_log_dir: tensorboard_log_dir
  Callbacks_dir: callbacks

source_download_dir:
  - ../outside_data/dog
  - ../outside_data/cat

local_data_dir:
  
  - data/dog
  - data/cat